/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = kern.services.FroniusSolarWebClient.Client.OpenAPIDateConverter;

namespace kern.services.FroniusSolarWebClient.Model
{
    /// <summary>
    /// UserAccountAttributes
    /// </summary>
    [DataContract(Name = "UserAccountAttributes")]
    public partial class UserAccountAttributes : IEquatable<UserAccountAttributes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserAccountAttributes" /> class.
        /// </summary>
        /// <param name="premiumMembership">premiumMembership.</param>
        /// <param name="termsAcceptedLatest">termsAcceptedLatest.</param>
        /// <param name="termsAcceptedVersion">termsAcceptedVersion.</param>
        public UserAccountAttributes(bool premiumMembership = default(bool), bool termsAcceptedLatest = default(bool), int termsAcceptedVersion = default(int))
        {
            this.PremiumMembership = premiumMembership;
            this.TermsAcceptedLatest = termsAcceptedLatest;
            this.TermsAcceptedVersion = termsAcceptedVersion;
        }

        /// <summary>
        /// Gets or Sets PremiumMembership
        /// </summary>
        [DataMember(Name = "premiumMembership", EmitDefaultValue = true)]
        public bool PremiumMembership { get; set; }

        /// <summary>
        /// Gets or Sets TermsAcceptedLatest
        /// </summary>
        [DataMember(Name = "termsAcceptedLatest", EmitDefaultValue = true)]
        public bool TermsAcceptedLatest { get; set; }

        /// <summary>
        /// Gets or Sets TermsAcceptedVersion
        /// </summary>
        [DataMember(Name = "termsAcceptedVersion", EmitDefaultValue = false)]
        public int TermsAcceptedVersion { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserAccountAttributes {\n");
            sb.Append("  PremiumMembership: ").Append(PremiumMembership).Append("\n");
            sb.Append("  TermsAcceptedLatest: ").Append(TermsAcceptedLatest).Append("\n");
            sb.Append("  TermsAcceptedVersion: ").Append(TermsAcceptedVersion).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserAccountAttributes);
        }

        /// <summary>
        /// Returns true if UserAccountAttributes instances are equal
        /// </summary>
        /// <param name="input">Instance of UserAccountAttributes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserAccountAttributes input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.PremiumMembership == input.PremiumMembership ||
                    this.PremiumMembership.Equals(input.PremiumMembership)
                ) && 
                (
                    this.TermsAcceptedLatest == input.TermsAcceptedLatest ||
                    this.TermsAcceptedLatest.Equals(input.TermsAcceptedLatest)
                ) && 
                (
                    this.TermsAcceptedVersion == input.TermsAcceptedVersion ||
                    this.TermsAcceptedVersion.Equals(input.TermsAcceptedVersion)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.PremiumMembership.GetHashCode();
                hashCode = (hashCode * 59) + this.TermsAcceptedLatest.GetHashCode();
                hashCode = (hashCode * 59) + this.TermsAcceptedVersion.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
