/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using kern.services.FroniusSolarWebClient.Client;
using kern.services.FroniusSolarWebClient.Api;
// uncomment below to import models
//using kern.services.FroniusSolarWebClient.Model;

namespace kern.services.FroniusSolarWebClient.Test.Api
{
    /// <summary>
    ///  Class for testing AggregatedApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AggregatedApiTests : IDisposable
    {
        private AggregatedApi instance;

        public AggregatedApiTests()
        {
            instance = new AggregatedApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggregatedApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AggregatedApi
            //Assert.IsType<AggregatedApi>(instance);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataGet(pvSystemId, channel);
            //Assert.IsType<AggregatedValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataYearsGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataYearsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataYearsGet(pvSystemId, channel);
            //Assert.IsType<AggregatedValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataYearsYearGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataYearsYearGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //int year = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataYearsYearGet(pvSystemId, year, channel);
            //Assert.IsType<AggregatedValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataYearsYearMonthsGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataYearsYearMonthsGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //int year = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataYearsYearMonthsGet(pvSystemId, year, channel);
            //Assert.IsType<AggregatedValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataYearsYearMonthsMonthDaysDayGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataYearsYearMonthsMonthDaysDayGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //int year = null;
            //int month = null;
            //int day = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataYearsYearMonthsMonthDaysDayGet(pvSystemId, year, month, day, channel);
            //Assert.IsType<AggregatedValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataYearsYearMonthsMonthDaysGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataYearsYearMonthsMonthDaysGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //int year = null;
            //int month = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataYearsYearMonthsMonthDaysGet(pvSystemId, year, month, channel);
            //Assert.IsType<AggregatedValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggdataYearsYearMonthsMonthGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggdataYearsYearMonthsMonthGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //int year = null;
            //int month = null;
            //string? channel = null;
            //var response = instance.PvsystemsPvSystemIdAggdataYearsYearMonthsMonthGet(pvSystemId, year, month, channel);
            //Assert.IsType<AggregatedValues>(response);
        }
    }
}
