/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using kern.services.FroniusSolarWebClient.Client;
using kern.services.FroniusSolarWebClient.Api;
// uncomment below to import models
//using kern.services.FroniusSolarWebClient.Model;

namespace kern.services.FroniusSolarWebClient.Test.Api
{
    /// <summary>
    ///  Class for testing AggregatedV2Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AggregatedV2ApiTests : IDisposable
    {
        private AggregatedV2Api instance;

        public AggregatedV2ApiTests()
        {
            instance = new AggregatedV2Api();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggregatedV2Api
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AggregatedV2Api
            //Assert.IsType<AggregatedV2Api>(instance);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdAggrdataGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdAggrdataGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //string? channel = null;
            //string? from = null;
            //string? to = null;
            //string? duration = null;
            //string? period = null;
            //int? offset = null;
            //int? limit = null;
            //var response = instance.PvsystemsPvSystemIdAggrdataGet(pvSystemId, channel, from, to, duration, period, offset, limit);
            //Assert.IsType<AggrValues>(response);
        }

        /// <summary>
        /// Test PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet
        /// </summary>
        [Fact]
        public void PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid pvSystemId = null;
            //Guid deviceId = null;
            //string? channel = null;
            //string? from = null;
            //string? to = null;
            //string? duration = null;
            //string? period = null;
            //int? offset = null;
            //int? limit = null;
            //var response = instance.PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet(pvSystemId, deviceId, channel, from, to, duration, period, offset, limit);
            //Assert.IsType<AggrValues>(response);
        }
    }
}
