/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using kern.services.FroniusSolarWebClient.Client;
using kern.services.FroniusSolarWebClient.Api;
// uncomment below to import models
//using kern.services.FroniusSolarWebClient.Model;

namespace kern.services.FroniusSolarWebClient.Test.Api
{
    /// <summary>
    ///  Class for testing TokensApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TokensApiTests : IDisposable
    {
        private TokensApi instance;

        public TokensApiTests()
        {
            instance = new TokensApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokensApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TokensApi
            //Assert.IsType<TokensApi>(instance);
        }

        /// <summary>
        /// Test IamJwtPost
        /// </summary>
        [Fact]
        public void IamJwtPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? scope = null;
            //InputNewToken? inputNewToken = null;
            //var response = instance.IamJwtPost(scope, inputNewToken);
            //Assert.IsType<Token>(response);
        }

        /// <summary>
        /// Test IamJwtRefreshTokenDelete
        /// </summary>
        [Fact]
        public void IamJwtRefreshTokenDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string refreshToken = null;
            //instance.IamJwtRefreshTokenDelete(refreshToken);
        }

        /// <summary>
        /// Test IamJwtRefreshTokenPatch
        /// </summary>
        [Fact]
        public void IamJwtRefreshTokenPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string refreshToken = null;
            //string? scope = null;
            //var response = instance.IamJwtRefreshTokenPatch(refreshToken, scope);
            //Assert.IsType<Token>(response);
        }
    }
}
