/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing AggData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AggDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AggData
        //private AggData instance;

        public AggDataTests()
        {
            // TODO uncomment below to create an instance of AggData
            //instance = new AggData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AggData
        /// </summary>
        [Fact]
        public void AggDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" AggData
            //Assert.IsType<AggData>(instance);
        }


        /// <summary>
        /// Test the property 'LogPeriod'
        /// </summary>
        [Fact]
        public void LogPeriodTest()
        {
            // TODO unit test for the property 'LogPeriod'
        }
        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

    }

}
