/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing DeviceIdsOnly
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceIdsOnlyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeviceIdsOnly
        //private DeviceIdsOnly instance;

        public DeviceIdsOnlyTests()
        {
            // TODO uncomment below to create an instance of DeviceIdsOnly
            //instance = new DeviceIdsOnly();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeviceIdsOnly
        /// </summary>
        [Fact]
        public void DeviceIdsOnlyInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeviceIdsOnly
            //Assert.IsType<DeviceIdsOnly>(instance);
        }


        /// <summary>
        /// Test the property 'DeviceIds'
        /// </summary>
        [Fact]
        public void DeviceIdsTest()
        {
            // TODO unit test for the property 'DeviceIds'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
