/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing HistoricalData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class HistoricalDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for HistoricalData
        //private HistoricalData instance;

        public HistoricalDataTests()
        {
            // TODO uncomment below to create an instance of HistoricalData
            //instance = new HistoricalData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of HistoricalData
        /// </summary>
        [Fact]
        public void HistoricalDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" HistoricalData
            //Assert.IsType<HistoricalData>(instance);
        }


        /// <summary>
        /// Test the property 'LogDateTime'
        /// </summary>
        [Fact]
        public void LogDateTimeTest()
        {
            // TODO unit test for the property 'LogDateTime'
        }
        /// <summary>
        /// Test the property 'LogDuration'
        /// </summary>
        [Fact]
        public void LogDurationTest()
        {
            // TODO unit test for the property 'LogDuration'
        }
        /// <summary>
        /// Test the property 'Channels'
        /// </summary>
        [Fact]
        public void ChannelsTest()
        {
            // TODO unit test for the property 'Channels'
        }

    }

}
