/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing PeakPower
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PeakPowerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PeakPower
        //private PeakPower instance;

        public PeakPowerTests()
        {
            // TODO uncomment below to create an instance of PeakPower
            //instance = new PeakPower();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PeakPower
        /// </summary>
        [Fact]
        public void PeakPowerInstanceTest()
        {
            // TODO uncomment below to test "IsType" PeakPower
            //Assert.IsType<PeakPower>(instance);
        }


        /// <summary>
        /// Test the property 'Dc1'
        /// </summary>
        [Fact]
        public void Dc1Test()
        {
            // TODO unit test for the property 'Dc1'
        }
        /// <summary>
        /// Test the property 'Dc2'
        /// </summary>
        [Fact]
        public void Dc2Test()
        {
            // TODO unit test for the property 'Dc2'
        }
        /// <summary>
        /// Test the property 'Dc3'
        /// </summary>
        [Fact]
        public void Dc3Test()
        {
            // TODO unit test for the property 'Dc3'
        }
        /// <summary>
        /// Test the property 'Dc4'
        /// </summary>
        [Fact]
        public void Dc4Test()
        {
            // TODO unit test for the property 'Dc4'
        }

    }

}
