/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing SystemMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SystemMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SystemMessage
        //private SystemMessage instance;

        public SystemMessageTests()
        {
            // TODO uncomment below to create an instance of SystemMessage
            //instance = new SystemMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SystemMessage
        /// </summary>
        [Fact]
        public void SystemMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" SystemMessage
            //Assert.IsType<SystemMessage>(instance);
        }


        /// <summary>
        /// Test the property 'PvSystemId'
        /// </summary>
        [Fact]
        public void PvSystemIdTest()
        {
            // TODO unit test for the property 'PvSystemId'
        }
        /// <summary>
        /// Test the property 'DeviceId'
        /// </summary>
        [Fact]
        public void DeviceIdTest()
        {
            // TODO unit test for the property 'DeviceId'
        }
        /// <summary>
        /// Test the property 'StateType'
        /// </summary>
        [Fact]
        public void StateTypeTest()
        {
            // TODO unit test for the property 'StateType'
        }
        /// <summary>
        /// Test the property 'StateCode'
        /// </summary>
        [Fact]
        public void StateCodeTest()
        {
            // TODO unit test for the property 'StateCode'
        }
        /// <summary>
        /// Test the property 'StateSeverity'
        /// </summary>
        [Fact]
        public void StateSeverityTest()
        {
            // TODO unit test for the property 'StateSeverity'
        }
        /// <summary>
        /// Test the property 'LogDateTime'
        /// </summary>
        [Fact]
        public void LogDateTimeTest()
        {
            // TODO unit test for the property 'LogDateTime'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Fact]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'DeviceName'
        /// </summary>
        [Fact]
        public void DeviceNameTest()
        {
            // TODO unit test for the property 'DeviceName'
        }

    }

}
