/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing UserInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserInfo
        //private UserInfo instance;

        public UserInfoTests()
        {
            // TODO uncomment below to create an instance of UserInfo
            //instance = new UserInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserInfo
        /// </summary>
        [Fact]
        public void UserInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserInfo
            //Assert.IsType<UserInfo>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'ContractInformation'
        /// </summary>
        [Fact]
        public void ContractInformationTest()
        {
            // TODO unit test for the property 'ContractInformation'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
        /// <summary>
        /// Test the property 'AccountAttributes'
        /// </summary>
        [Fact]
        public void AccountAttributesTest()
        {
            // TODO unit test for the property 'AccountAttributes'
        }

    }

}
