/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing UserInfoAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserInfoAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserInfoAddress
        //private UserInfoAddress instance;

        public UserInfoAddressTests()
        {
            // TODO uncomment below to create an instance of UserInfoAddress
            //instance = new UserInfoAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserInfoAddress
        /// </summary>
        [Fact]
        public void UserInfoAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserInfoAddress
            //Assert.IsType<UserInfoAddress>(instance);
        }


        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Fact]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'ZipCode'
        /// </summary>
        [Fact]
        public void ZipCodeTest()
        {
            // TODO unit test for the property 'ZipCode'
        }
        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
