/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing UserInfoSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserInfoSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserInfoSettings
        //private UserInfoSettings instance;

        public UserInfoSettingsTests()
        {
            // TODO uncomment below to create an instance of UserInfoSettings
            //instance = new UserInfoSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserInfoSettings
        /// </summary>
        [Fact]
        public void UserInfoSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserInfoSettings
            //Assert.IsType<UserInfoSettings>(instance);
        }


        /// <summary>
        /// Test the property 'TimeZone'
        /// </summary>
        [Fact]
        public void TimeZoneTest()
        {
            // TODO unit test for the property 'TimeZone'
        }
        /// <summary>
        /// Test the property 'DateFormat'
        /// </summary>
        [Fact]
        public void DateFormatTest()
        {
            // TODO unit test for the property 'DateFormat'
        }
        /// <summary>
        /// Test the property 'TimeFormat'
        /// </summary>
        [Fact]
        public void TimeFormatTest()
        {
            // TODO unit test for the property 'TimeFormat'
        }
        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

    }

}
