/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using kern.services.FroniusSolarWebClient.Api;
using kern.services.FroniusSolarWebClient.Model;
using kern.services.FroniusSolarWebClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace kern.services.FroniusSolarWebClient.Test.Model
{
    /// <summary>
    ///  Class for testing UserAccountAttributes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAccountAttributesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAccountAttributes
        //private UserAccountAttributes instance;

        public UserAccountAttributesTests()
        {
            // TODO uncomment below to create an instance of UserAccountAttributes
            //instance = new UserAccountAttributes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAccountAttributes
        /// </summary>
        [Fact]
        public void UserAccountAttributesInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserAccountAttributes
            //Assert.IsType<UserAccountAttributes>(instance);
        }


        /// <summary>
        /// Test the property 'PremiumMembership'
        /// </summary>
        [Fact]
        public void PremiumMembershipTest()
        {
            // TODO unit test for the property 'PremiumMembership'
        }
        /// <summary>
        /// Test the property 'TermsAcceptedLatest'
        /// </summary>
        [Fact]
        public void TermsAcceptedLatestTest()
        {
            // TODO unit test for the property 'TermsAcceptedLatest'
        }
        /// <summary>
        /// Test the property 'TermsAcceptedVersion'
        /// </summary>
        [Fact]
        public void TermsAcceptedVersionTest()
        {
            // TODO unit test for the property 'TermsAcceptedVersion'
        }

    }

}
