/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using kern.services.FroniusSolarWebClient.Client;
using kern.services.FroniusSolarWebClient.Model;

namespace kern.services.FroniusSolarWebClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAggregatedV2ApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AggrValues</returns>
        AggrValues PvsystemsPvSystemIdAggrdataGet(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0);

        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AggrValues</returns>
        ApiResponse<AggrValues> PvsystemsPvSystemIdAggrdataGetWithHttpInfo(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0);
        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AggrValues</returns>
        AggrValues PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0);

        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AggrValues</returns>
        ApiResponse<AggrValues> PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetWithHttpInfo(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAggregatedV2ApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AggrValues</returns>
        System.Threading.Tasks.Task<AggrValues> PvsystemsPvSystemIdAggrdataGetAsync(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AggrValues)</returns>
        System.Threading.Tasks.Task<ApiResponse<AggrValues>> PvsystemsPvSystemIdAggrdataGetWithHttpInfoAsync(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AggrValues</returns>
        System.Threading.Tasks.Task<AggrValues> PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetAsync(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AggrValues)</returns>
        System.Threading.Tasks.Task<ApiResponse<AggrValues>> PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetWithHttpInfoAsync(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAggregatedV2Api : IAggregatedV2ApiSync, IAggregatedV2ApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AggregatedV2Api : IAggregatedV2Api
    {
        private kern.services.FroniusSolarWebClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatedV2Api"/> class.
        /// </summary>
        /// <returns></returns>
        public AggregatedV2Api() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatedV2Api"/> class.
        /// </summary>
        /// <returns></returns>
        public AggregatedV2Api(string basePath)
        {
            this.Configuration = kern.services.FroniusSolarWebClient.Client.Configuration.MergeConfigurations(
                kern.services.FroniusSolarWebClient.Client.GlobalConfiguration.Instance,
                new kern.services.FroniusSolarWebClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = kern.services.FroniusSolarWebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatedV2Api"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AggregatedV2Api(kern.services.FroniusSolarWebClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = kern.services.FroniusSolarWebClient.Client.Configuration.MergeConfigurations(
                kern.services.FroniusSolarWebClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = kern.services.FroniusSolarWebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AggregatedV2Api"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AggregatedV2Api(kern.services.FroniusSolarWebClient.Client.ISynchronousClient client, kern.services.FroniusSolarWebClient.Client.IAsynchronousClient asyncClient, kern.services.FroniusSolarWebClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = kern.services.FroniusSolarWebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public kern.services.FroniusSolarWebClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public kern.services.FroniusSolarWebClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public kern.services.FroniusSolarWebClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public kern.services.FroniusSolarWebClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AggrValues</returns>
        public AggrValues PvsystemsPvSystemIdAggrdataGet(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues> localVarResponse = PvsystemsPvSystemIdAggrdataGetWithHttpInfo(pvSystemId, channel, from, to, duration, period, offset, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AggrValues</returns>
        public kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues> PvsystemsPvSystemIdAggrdataGetWithHttpInfo(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }
            if (period != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "period", period));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "AggregatedV2Api.PvsystemsPvSystemIdAggrdataGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AggrValues>("/pvsystems/{pvSystemId}/aggrdata", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdAggrdataGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AggrValues</returns>
        public async System.Threading.Tasks.Task<AggrValues> PvsystemsPvSystemIdAggrdataGetAsync(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues> localVarResponse = await PvsystemsPvSystemIdAggrdataGetWithHttpInfoAsync(pvSystemId, channel, from, to, duration, period, offset, limit, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets aggregated data for a given PV system for a custom period of time. Filters allow limiting to specific PV system energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AggrValues)</returns>
        public async System.Threading.Tasks.Task<kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues>> PvsystemsPvSystemIdAggrdataGetWithHttpInfoAsync(Guid pvSystemId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }
            if (period != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "period", period));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "AggregatedV2Api.PvsystemsPvSystemIdAggrdataGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<AggrValues>("/pvsystems/{pvSystemId}/aggrdata", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdAggrdataGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AggrValues</returns>
        public AggrValues PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues> localVarResponse = PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetWithHttpInfo(pvSystemId, deviceId, channel, from, to, duration, period, offset, limit);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AggrValues</returns>
        public kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues> PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetWithHttpInfo(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            localVarRequestOptions.PathParameters.Add("deviceId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(deviceId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }
            if (period != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "period", period));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "AggregatedV2Api.PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AggrValues>("/pvsystems/{pvSystemId}/devices/{deviceId}/aggrdata", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AggrValues</returns>
        public async System.Threading.Tasks.Task<AggrValues> PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetAsync(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues> localVarResponse = await PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetWithHttpInfoAsync(pvSystemId, deviceId, channel, from, to, duration, period, offset, limit, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Gets aggregated data for a given inverter for a custom period of time. Filters allow limiting to specific device energy values.  Note: If period parameter is used, than from, to and duration parameters are not allowed, and vice versa. 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="deviceId"></param>
        /// <param name="channel">Limits query by selected channel. Note: Channel filters can be concatened using commas. E.g,: ?channel&#x3D;EnergyFeedIn,EnergyPurchased (optional)</param>
        /// <param name="from">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="to">​Limits the time series for the query. Period type in from and to need to match. Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="duration">Duration is measured in years, months or days - depending on the from parameter. A duration of 1 means that start and end are equal.  Formats: yyyy for years, yyyy-MM or yyyyMM for months, yyyy-MM-dd or yyyyMMdd for days. (optional)</param>
        /// <param name="period">Limits the time series for the query to a period. \&quot;total\&quot; delivers total values over whole system lifetime. \&quot;years\&quot; delivers values for each year of system lifetime. \&quot;yyyy\&quot; delivers all months of requested year. \&quot;yyyy-MM\&quot; delivers all days of requested month. (optional)</param>
        /// <param name="offset">​Supports pagination, returns items from a starting \&quot;offset\&quot; point (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="limit">​Supports pagination, returning not more than \&quot;limit\&quot; items (items &#x3D; objects in the \&quot;Data\&quot; array). (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AggrValues)</returns>
        public async System.Threading.Tasks.Task<kern.services.FroniusSolarWebClient.Client.ApiResponse<AggrValues>> PvsystemsPvSystemIdDevicesDeviceIdAggrdataGetWithHttpInfoAsync(Guid pvSystemId, Guid deviceId, string? channel = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), string? period = default(string?), int? offset = default(int?), int? limit = default(int?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            localVarRequestOptions.PathParameters.Add("deviceId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(deviceId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }
            if (period != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "period", period));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }

            localVarRequestOptions.Operation = "AggregatedV2Api.PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<AggrValues>("/pvsystems/{pvSystemId}/devices/{deviceId}/aggrdata", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdDevicesDeviceIdAggrdataGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
