/*
 * Solar.web Query API (SWQAPI)
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using kern.services.FroniusSolarWebClient.Client;
using kern.services.FroniusSolarWebClient.Model;

namespace kern.services.FroniusSolarWebClient.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMeteoApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// This method returns current weather forecast for PV System
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>WeatherForecast</returns>
        WeatherForecast PvsystemsPvSystemIdWeatherCurrentGet(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0);

        /// <summary>
        /// This method returns current weather forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of WeatherForecast</returns>
        ApiResponse<WeatherForecast> PvsystemsPvSystemIdWeatherCurrentGetWithHttpInfo(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0);
        /// <summary>
        /// This method returns energy forecast for PV System
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EnergyForecast</returns>
        EnergyForecast PvsystemsPvSystemIdWeatherEnergyforecastGet(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0);

        /// <summary>
        /// This method returns energy forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EnergyForecast</returns>
        ApiResponse<EnergyForecast> PvsystemsPvSystemIdWeatherEnergyforecastGetWithHttpInfo(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0);
        /// <summary>
        /// This method returns weather forecast for PV System
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>WeatherForecast</returns>
        WeatherForecast PvsystemsPvSystemIdWeatherForecastGet(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0);

        /// <summary>
        /// This method returns weather forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of WeatherForecast</returns>
        ApiResponse<WeatherForecast> PvsystemsPvSystemIdWeatherForecastGetWithHttpInfo(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMeteoApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// This method returns current weather forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WeatherForecast</returns>
        System.Threading.Tasks.Task<WeatherForecast> PvsystemsPvSystemIdWeatherCurrentGetAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// This method returns current weather forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WeatherForecast)</returns>
        System.Threading.Tasks.Task<ApiResponse<WeatherForecast>> PvsystemsPvSystemIdWeatherCurrentGetWithHttpInfoAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// This method returns energy forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EnergyForecast</returns>
        System.Threading.Tasks.Task<EnergyForecast> PvsystemsPvSystemIdWeatherEnergyforecastGetAsync(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// This method returns energy forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EnergyForecast)</returns>
        System.Threading.Tasks.Task<ApiResponse<EnergyForecast>> PvsystemsPvSystemIdWeatherEnergyforecastGetWithHttpInfoAsync(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// This method returns weather forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WeatherForecast</returns>
        System.Threading.Tasks.Task<WeatherForecast> PvsystemsPvSystemIdWeatherForecastGetAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// This method returns weather forecast for PV System
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WeatherForecast)</returns>
        System.Threading.Tasks.Task<ApiResponse<WeatherForecast>> PvsystemsPvSystemIdWeatherForecastGetWithHttpInfoAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IMeteoApi : IMeteoApiSync, IMeteoApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class MeteoApi : IMeteoApi
    {
        private kern.services.FroniusSolarWebClient.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="MeteoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MeteoApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeteoApi"/> class.
        /// </summary>
        /// <returns></returns>
        public MeteoApi(string basePath)
        {
            this.Configuration = kern.services.FroniusSolarWebClient.Client.Configuration.MergeConfigurations(
                kern.services.FroniusSolarWebClient.Client.GlobalConfiguration.Instance,
                new kern.services.FroniusSolarWebClient.Client.Configuration { BasePath = basePath }
            );
            this.Client = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = kern.services.FroniusSolarWebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeteoApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public MeteoApi(kern.services.FroniusSolarWebClient.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = kern.services.FroniusSolarWebClient.Client.Configuration.MergeConfigurations(
                kern.services.FroniusSolarWebClient.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new kern.services.FroniusSolarWebClient.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = kern.services.FroniusSolarWebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="MeteoApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public MeteoApi(kern.services.FroniusSolarWebClient.Client.ISynchronousClient client, kern.services.FroniusSolarWebClient.Client.IAsynchronousClient asyncClient, kern.services.FroniusSolarWebClient.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = kern.services.FroniusSolarWebClient.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public kern.services.FroniusSolarWebClient.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public kern.services.FroniusSolarWebClient.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public kern.services.FroniusSolarWebClient.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public kern.services.FroniusSolarWebClient.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// This method returns current weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>WeatherForecast</returns>
        public WeatherForecast PvsystemsPvSystemIdWeatherCurrentGet(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast> localVarResponse = PvsystemsPvSystemIdWeatherCurrentGetWithHttpInfo(pvSystemId, channel, timezone);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This method returns current weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of WeatherForecast</returns>
        public kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast> PvsystemsPvSystemIdWeatherCurrentGetWithHttpInfo(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (timezone != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "timezone", timezone));
            }

            localVarRequestOptions.Operation = "MeteoApi.PvsystemsPvSystemIdWeatherCurrentGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<WeatherForecast>("/pvsystems/{pvSystemId}/weather/current", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdWeatherCurrentGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This method returns current weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WeatherForecast</returns>
        public async System.Threading.Tasks.Task<WeatherForecast> PvsystemsPvSystemIdWeatherCurrentGetAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast> localVarResponse = await PvsystemsPvSystemIdWeatherCurrentGetWithHttpInfoAsync(pvSystemId, channel, timezone, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This method returns current weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WeatherForecast)</returns>
        public async System.Threading.Tasks.Task<kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast>> PvsystemsPvSystemIdWeatherCurrentGetWithHttpInfoAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (timezone != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "timezone", timezone));
            }

            localVarRequestOptions.Operation = "MeteoApi.PvsystemsPvSystemIdWeatherCurrentGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<WeatherForecast>("/pvsystems/{pvSystemId}/weather/current", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdWeatherCurrentGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This method returns energy forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>EnergyForecast</returns>
        public EnergyForecast PvsystemsPvSystemIdWeatherEnergyforecastGet(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<EnergyForecast> localVarResponse = PvsystemsPvSystemIdWeatherEnergyforecastGetWithHttpInfo(pvSystemId, timezone, from, to, duration);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This method returns energy forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of EnergyForecast</returns>
        public kern.services.FroniusSolarWebClient.Client.ApiResponse<EnergyForecast> PvsystemsPvSystemIdWeatherEnergyforecastGetWithHttpInfo(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (timezone != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "timezone", timezone));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }

            localVarRequestOptions.Operation = "MeteoApi.PvsystemsPvSystemIdWeatherEnergyforecastGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<EnergyForecast>("/pvsystems/{pvSystemId}/weather/energyforecast", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdWeatherEnergyforecastGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This method returns energy forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of EnergyForecast</returns>
        public async System.Threading.Tasks.Task<EnergyForecast> PvsystemsPvSystemIdWeatherEnergyforecastGetAsync(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<EnergyForecast> localVarResponse = await PvsystemsPvSystemIdWeatherEnergyforecastGetWithHttpInfoAsync(pvSystemId, timezone, from, to, duration, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This method returns energy forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-ddTHH:mm:ssZ or yyyyMMddTHHmmssZ. (optional)</param>
        /// <param name="duration">Number of hours in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (EnergyForecast)</returns>
        public async System.Threading.Tasks.Task<kern.services.FroniusSolarWebClient.Client.ApiResponse<EnergyForecast>> PvsystemsPvSystemIdWeatherEnergyforecastGetWithHttpInfoAsync(Guid pvSystemId, string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (timezone != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "timezone", timezone));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }

            localVarRequestOptions.Operation = "MeteoApi.PvsystemsPvSystemIdWeatherEnergyforecastGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<EnergyForecast>("/pvsystems/{pvSystemId}/weather/energyforecast", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdWeatherEnergyforecastGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This method returns weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>WeatherForecast</returns>
        public WeatherForecast PvsystemsPvSystemIdWeatherForecastGet(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast> localVarResponse = PvsystemsPvSystemIdWeatherForecastGetWithHttpInfo(pvSystemId, channel, timezone, from, to, duration);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This method returns weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of WeatherForecast</returns>
        public kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast> PvsystemsPvSystemIdWeatherForecastGetWithHttpInfo(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0)
        {
            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (timezone != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "timezone", timezone));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }

            localVarRequestOptions.Operation = "MeteoApi.PvsystemsPvSystemIdWeatherForecastGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<WeatherForecast>("/pvsystems/{pvSystemId}/weather/forecast", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdWeatherForecastGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// This method returns weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of WeatherForecast</returns>
        public async System.Threading.Tasks.Task<WeatherForecast> PvsystemsPvSystemIdWeatherForecastGetAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast> localVarResponse = await PvsystemsPvSystemIdWeatherForecastGetWithHttpInfoAsync(pvSystemId, channel, timezone, from, to, duration, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// This method returns weather forecast for PV System 
        /// </summary>
        /// <exception cref="kern.services.FroniusSolarWebClient.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="pvSystemId"></param>
        /// <param name="channel"> (optional)</param>
        /// <param name="timezone">Timezone for dates in response, \&quot;local\&quot; or \&quot;zulu\&quot;. Zulu is default. (optional)</param>
        /// <param name="from">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="to">Date time format yyyy-MM-dd or yyyyMMdd. (optional)</param>
        /// <param name="duration">Number of days in response. (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (WeatherForecast)</returns>
        public async System.Threading.Tasks.Task<kern.services.FroniusSolarWebClient.Client.ApiResponse<WeatherForecast>> PvsystemsPvSystemIdWeatherForecastGetWithHttpInfoAsync(Guid pvSystemId, string? channel = default(string?), string? timezone = default(string?), string? from = default(string?), string? to = default(string?), string? duration = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            kern.services.FroniusSolarWebClient.Client.RequestOptions localVarRequestOptions = new kern.services.FroniusSolarWebClient.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = kern.services.FroniusSolarWebClient.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("pvSystemId", kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToString(pvSystemId)); // path parameter
            if (channel != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "channel", channel));
            }
            if (timezone != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "timezone", timezone));
            }
            if (from != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "from", from));
            }
            if (to != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "to", to));
            }
            if (duration != null)
            {
                localVarRequestOptions.QueryParameters.Add(kern.services.FroniusSolarWebClient.Client.ClientUtils.ParameterToMultiMap("", "duration", duration));
            }

            localVarRequestOptions.Operation = "MeteoApi.PvsystemsPvSystemIdWeatherForecastGet";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (AccessKeyId) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyId")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyId", this.Configuration.GetApiKeyWithPrefix("AccessKeyId"));
            }
            // authentication (AccessKeyValue) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("AccessKeyValue")))
            {
                localVarRequestOptions.HeaderParameters.Add("AccessKeyValue", this.Configuration.GetApiKeyWithPrefix("AccessKeyValue"));
            }
            // authentication (Bearer) required
            if (!string.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("Authorization")))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", this.Configuration.GetApiKeyWithPrefix("Authorization"));
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<WeatherForecast>("/pvsystems/{pvSystemId}/weather/forecast", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("PvsystemsPvSystemIdWeatherForecastGet", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
